/*
 * HTTPRoute
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.examples.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.examples.models.HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * ResponseHeaderModifier defines a schema for a filter that modifies response headers.   Support: Extended
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier {
  public static final String SERIALIZED_NAME_ADD = "add";
  @SerializedName(SERIALIZED_NAME_ADD)
  private List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> add;

  public static final String SERIALIZED_NAME_REMOVE = "remove";
  @SerializedName(SERIALIZED_NAME_REMOVE)
  private List<String> remove;

  public static final String SERIALIZED_NAME_SET = "set";
  @SerializedName(SERIALIZED_NAME_SET)
  private List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> set;

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier() {
  }

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier add(List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> add) {
    
    this.add = add;
    return this;
  }

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier addAddItem(HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner addItem) {
    if (this.add == null) {
      this.add = new ArrayList<>();
    }
    this.add.add(addItem);
    return this;
  }

   /**
   * Add adds the given header(s) (name, value) to the request before the action. It appends to any existing values associated with the header name.   Input:   GET /foo HTTP/1.1   my-header: foo   Config:   add:   - name: \&quot;my-header\&quot;     value: \&quot;bar,baz\&quot;   Output:   GET /foo HTTP/1.1   my-header: foo,bar,baz
   * @return add
  **/
  @javax.annotation.Nullable

  public List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> getAdd() {
    return add;
  }


  public void setAdd(List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> add) {
    this.add = add;
  }


  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier remove(List<String> remove) {
    
    this.remove = remove;
    return this;
  }

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier addRemoveItem(String removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

   /**
   * Remove the given header(s) from the HTTP request before the action. The value of Remove is a list of HTTP header names. Note that the header names are case-insensitive (see https://datatracker.ietf.org/doc/html/rfc2616#section-4.2).   Input:   GET /foo HTTP/1.1   my-header1: foo   my-header2: bar   my-header3: baz   Config:   remove: [\&quot;my-header1\&quot;, \&quot;my-header3\&quot;]   Output:   GET /foo HTTP/1.1   my-header2: bar
   * @return remove
  **/
  @javax.annotation.Nullable

  public List<String> getRemove() {
    return remove;
  }


  public void setRemove(List<String> remove) {
    this.remove = remove;
  }


  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier set(List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> set) {
    
    this.set = set;
    return this;
  }

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier addSetItem(HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner setItem) {
    if (this.set == null) {
      this.set = new ArrayList<>();
    }
    this.set.add(setItem);
    return this;
  }

   /**
   * Set overwrites the request with the given header (name, value) before the action.   Input:   GET /foo HTTP/1.1   my-header: foo   Config:   set:   - name: \&quot;my-header\&quot;     value: \&quot;bar\&quot;   Output:   GET /foo HTTP/1.1   my-header: bar
   * @return set
  **/
  @javax.annotation.Nullable

  public List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> getSet() {
    return set;
  }


  public void setSet(List<HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner> set) {
    this.set = set;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier = (HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier) o;
    return Objects.equals(this.add, htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier.add) &&
        Objects.equals(this.remove, htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier.remove) &&
        Objects.equals(this.set, htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier.set);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, remove, set);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerResponseHeaderModifier {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

