/*
 * HTTPRoute
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.examples.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.examples.models.HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewritePath;
import java.io.IOException;

/**
 * URLRewrite defines a schema for a filter that modifies a request during forwarding.   Support: Extended
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite {
  public static final String SERIALIZED_NAME_HOSTNAME = "hostname";
  @SerializedName(SERIALIZED_NAME_HOSTNAME)
  private String hostname;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewritePath path;

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite() {
  }

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite hostname(String hostname) {
    
    this.hostname = hostname;
    return this;
  }

   /**
   * Hostname is the value to be used to replace the Host header value during forwarding.   Support: Extended
   * @return hostname
  **/
  @javax.annotation.Nullable

  public String getHostname() {
    return hostname;
  }


  public void setHostname(String hostname) {
    this.hostname = hostname;
  }


  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite path(HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewritePath path) {
    
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @javax.annotation.Nullable

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewritePath getPath() {
    return path;
  }


  public void setPath(HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewritePath path) {
    this.path = path;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite = (HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite) o;
    return Objects.equals(this.hostname, htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite.hostname) &&
        Objects.equals(this.path, htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostname, path);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerUrlRewrite {\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

