/*
 * HTTPRoute
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.examples.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * HTTPHeader represents an HTTP Header name and value as defined by RFC 7230.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner() {
  }

  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is the name of the HTTP Header to be matched. Name matching MUST be case insensitive. (See https://tools.ietf.org/html/rfc7230#section-3.2).   If multiple entries specify equivalent header names, the first entry with an equivalent name MUST be considered for a match. Subsequent entries with an equivalent header name MUST be ignored. Due to the case-insensitivity of header names, \&quot;foo\&quot; and \&quot;Foo\&quot; are considered equivalent.
   * @return name
  **/
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Value is the value of HTTP Header to be matched.
   * @return value
  **/
  @javax.annotation.Nonnull

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner = (HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner) o;
    return Objects.equals(this.name, htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner.name) &&
        Objects.equals(this.value, htTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestHeaderModifierAddInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

