apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
spec:
  provider: gatewayapi:v1
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  service:
    port: 9898
    targetPort: 9898
    portDiscovery: true
    hosts:
    - "podinfo.example.com"
    gatewayRefs:
    - name: contour
      namespace: projectcontour
  analysis:
    interval: 10s
    threshold: 1
    maxWeight: 10
    stepWeight: 5
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 5000
      interval: 30s
