apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway
spec:
  count: 1

---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: podinfo
spec:
  service:
    name: podinfo
  routes:
  - uri: http://podinfo:9898
    predicates:
    - Path=/podinfo
    filters:
    - StripPrefix=1
  - uri: http://podinfo-canary:9898
    predicates:
    - Path=/canary
    filters:
    - StripPrefix=1

---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: gateway-mapping
spec:
  gatewayRef:
    name: gateway
  routeConfigRef:
    name: podinfo
